<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>IncidentIQ.Api</RootNamespace>
    <AssemblyName>IncidentIQ.Api</AssemblyName>
    <UserSecretsId>incidentiq-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../persistence/IncidentIQ.Persistence.csproj" />
    <ProjectReference Include="../shared/IncidentIQ.Shared.csproj" />
  </ItemGroup>

</Project>
