// <auto-generated />
using System;
using IncidentIQ.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace IncidentIQ.Persistence.Migrations
{
    [DbContext(typeof(IncidentIQDbContext))]
    [Migration("20260824214019_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IncidentIQ.Domain.Entities.AiAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AnalysisVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("analysis_version");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("embedding_model");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("ModelProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_provider");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ProbableCause")
                        .HasColumnType("text")
                        .HasColumnName("probable_cause");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("SimilarIncidents")
                        .HasColumnType("jsonb")
                        .HasColumnName("similar_incidents");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SuggestedActions")
                        .HasColumnType("jsonb")
                        .HasColumnName("suggested_actions");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_ai_analyses");

                    b.HasIndex("IncidentId", "AnalysisVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_ai_analyses_incident_id_analysis_version");

                    b.HasIndex("OrganizationId", "IncidentId")
                        .HasDatabaseName("ix_ai_analyses_organization_id_incident_id");

                    b.ToTable("ai_analyses", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Changes")
                        .HasColumnType("jsonb")
                        .HasColumnName("changes");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_logs_actor_user_id");

                    b.HasIndex("OrganizationId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_organization_id_occurred_at");

                    b.HasIndex("OrganizationId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_organization_id_entity_type_entity_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("DeployedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deployed_at");

                    b.Property<string>("DeployedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deployed_by");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("MonitoredServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitored_service_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("OrganizationId", "EnvironmentId")
                        .HasDatabaseName("ix_deployments_organization_id_environment_id");

                    b.HasIndex("OrganizationId", "MonitoredServiceId", "EnvironmentId", "DeployedAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_deployments_organization_id_monitored_service_id_environmen");

                    b.ToTable("deployments", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsProduction")
                        .HasColumnType("boolean")
                        .HasColumnName("is_production");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_environments");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_environments_organization_id_id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_environments_organization_id_key");

                    b.ToTable("environments", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("LogPatternId")
                        .HasColumnType("uuid")
                        .HasColumnName("log_pattern_id");

                    b.Property<Guid>("MonitoredServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitored_service_id");

                    b.Property<long>("OccurrenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("occurrence_count");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("text")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by_user_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SuspectedDeploymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("suspected_deployment_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_incidents_organization_id_id");

                    b.HasIndex("SuspectedDeploymentId")
                        .HasDatabaseName("ix_incidents_suspected_deployment_id");

                    b.HasIndex("OrganizationId", "EnvironmentId")
                        .HasDatabaseName("ix_incidents_organization_id_environment_id");

                    b.HasIndex("OrganizationId", "LogPatternId")
                        .IsUnique()
                        .HasDatabaseName("ux_incidents_active_pattern")
                        .HasFilter("status IN ('Open', 'Acknowledged')");

                    b.HasIndex("OrganizationId", "MonitoredServiceId")
                        .HasDatabaseName("ix_incidents_organization_id_monitored_service_id");

                    b.HasIndex("OrganizationId", "Status", "LastSeenAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_incidents_organization_id_status_last_seen_at");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.IncidentEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_incident_events");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_incident_events_actor_user_id");

                    b.HasIndex("OrganizationId", "IncidentId", "OccurredAt")
                        .HasDatabaseName("ix_incident_events_organization_id_incident_id_occurred_at");

                    b.ToTable("incident_events", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.LogEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exception_type");

                    b.Property<string>("Host")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<Guid?>("LogPatternId")
                        .HasColumnType("uuid")
                        .HasColumnName("log_pattern_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("message");

                    b.Property<Guid>("MonitoredServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitored_service_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("SpanId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("span_id");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text")
                        .HasColumnName("stack_trace");

                    b.Property<string>("TraceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("trace_id");

                    b.HasKey("Id")
                        .HasName("pk_log_events");

                    b.HasIndex("IncidentId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_log_events_incident_id_occurred_at")
                        .HasFilter("incident_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "EnvironmentId")
                        .HasDatabaseName("ix_log_events_organization_id_environment_id");

                    b.HasIndex("OrganizationId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("ix_log_events_organization_id_event_id");

                    b.HasIndex("OrganizationId", "IncidentId")
                        .HasDatabaseName("ix_log_events_organization_id_incident_id");

                    b.HasIndex("OrganizationId", "MonitoredServiceId")
                        .HasDatabaseName("ix_log_events_organization_id_monitored_service_id");

                    b.HasIndex("OrganizationId", "TraceId")
                        .HasDatabaseName("ix_log_events_organization_id_trace_id")
                        .HasFilter("trace_id IS NOT NULL");

                    b.HasIndex("OrganizationId", "LogPatternId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_log_events_organization_id_log_pattern_id_occurred_at")
                        .HasFilter("log_pattern_id IS NOT NULL");

                    b.ToTable("log_events", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.LogPattern", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("environment_id");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exception_type");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_muted");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message_template");

                    b.Property<Guid>("MonitoredServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("monitored_service_id");

                    b.Property<long>("OccurrenceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("occurrence_count");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("SampleMessage")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("sample_message");

                    b.Property<string>("TopStackFrames")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("top_stack_frames");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_log_patterns");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_log_patterns_organization_id_id");

                    b.HasIndex("OrganizationId", "EnvironmentId")
                        .HasDatabaseName("ix_log_patterns_organization_id_environment_id");

                    b.HasIndex("OrganizationId", "Fingerprint")
                        .IsUnique()
                        .HasDatabaseName("ix_log_patterns_organization_id_fingerprint");

                    b.HasIndex("OrganizationId", "MonitoredServiceId", "EnvironmentId", "LastSeenAt")
                        .IsDescending(false, false, false, true)
                        .HasDatabaseName("ix_log_patterns_organization_id_monitored_service_id_environme");

                    b.ToTable("log_patterns", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.MonitoredService", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("OwnerTeam")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_team");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_monitored_services");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_monitored_services_organization_id_id");

                    b.HasIndex("OrganizationId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_monitored_services_organization_id_key");

                    b.ToTable("monitored_services", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LogRetentionDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90)
                        .HasColumnName("log_retention_days");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_organizations_slug");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb")
                        .HasColumnName("headers");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.ProcessedEvent", b =>
                {
                    b.Property<string>("ConsumerGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("consumer_group");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("ConsumerGroup", "EventId")
                        .HasName("pk_processed_events");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_processed_events_expires_at");

                    b.ToTable("processed_events", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_role");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("OrganizationId", "Id")
                        .HasName("ak_users_organization_id_id");

                    b.HasIndex("OrganizationId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_organization_id_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("OrganizationId", "UserId")
                        .HasDatabaseName("ix_user_roles_organization_id_user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.AiAnalysis", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.Incident", "Incident")
                        .WithMany("Analyses")
                        .HasForeignKey("OrganizationId", "IncidentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_analyses_incidents_organization_id_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_logs_users_actor_user_id");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Deployment", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EnvironmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_environments_organization_id_environment_id");

                    b.HasOne("IncidentIQ.Domain.Entities.MonitoredService", "MonitoredService")
                        .WithMany("Deployments")
                        .HasForeignKey("OrganizationId", "MonitoredServiceId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_monitored_services_organization_id_monitored_se");

                    b.Navigation("Environment");

                    b.Navigation("MonitoredService");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Environment", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.Organization", "Organization")
                        .WithMany("Environments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_environments_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Incident", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.Deployment", "SuspectedDeployment")
                        .WithMany()
                        .HasForeignKey("SuspectedDeploymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incidents_deployments_suspected_deployment_id");

                    b.HasOne("IncidentIQ.Domain.Entities.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EnvironmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_environments_organization_id_environment_id");

                    b.HasOne("IncidentIQ.Domain.Entities.LogPattern", "LogPattern")
                        .WithMany("Incidents")
                        .HasForeignKey("OrganizationId", "LogPatternId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_log_patterns_organization_id_log_pattern_id");

                    b.HasOne("IncidentIQ.Domain.Entities.MonitoredService", "MonitoredService")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MonitoredServiceId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_monitored_services_organization_id_monitored_serv");

                    b.Navigation("Environment");

                    b.Navigation("LogPattern");

                    b.Navigation("MonitoredService");

                    b.Navigation("SuspectedDeployment");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.IncidentEvent", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_incident_events_users_actor_user_id");

                    b.HasOne("IncidentIQ.Domain.Entities.Incident", "Incident")
                        .WithMany("Events")
                        .HasForeignKey("OrganizationId", "IncidentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incident_events_incidents_organization_id_incident_id");

                    b.Navigation("ActorUser");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.LogEvent", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EnvironmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_events_environments_organization_id_environment_id");

                    b.HasOne("IncidentIQ.Domain.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "IncidentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_log_events_incidents_organization_id_incident_id");

                    b.HasOne("IncidentIQ.Domain.Entities.LogPattern", "LogPattern")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "LogPatternId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_log_events_log_patterns_organization_id_log_pattern_id");

                    b.HasOne("IncidentIQ.Domain.Entities.MonitoredService", "MonitoredService")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "MonitoredServiceId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_events_monitored_services_organization_id_monitored_ser");

                    b.Navigation("Environment");

                    b.Navigation("Incident");

                    b.Navigation("LogPattern");

                    b.Navigation("MonitoredService");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.LogPattern", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.Environment", "Environment")
                        .WithMany()
                        .HasForeignKey("OrganizationId", "EnvironmentId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_patterns_environments_organization_id_environment_id");

                    b.HasOne("IncidentIQ.Domain.Entities.MonitoredService", "MonitoredService")
                        .WithMany("LogPatterns")
                        .HasForeignKey("OrganizationId", "MonitoredServiceId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_patterns_monitored_services_organization_id_monitored_s");

                    b.Navigation("Environment");

                    b.Navigation("MonitoredService");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.MonitoredService", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.Organization", "Organization")
                        .WithMany("MonitoredServices")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_monitored_services_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.User", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("IncidentIQ.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("IncidentIQ.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("OrganizationId", "UserId")
                        .HasPrincipalKey("OrganizationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_organization_id_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Incident", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.LogPattern", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.MonitoredService", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("LogPatterns");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Environments");

                    b.Navigation("MonitoredServices");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IncidentIQ.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
